---

- name: Check if nextcloud service is running
  shell: docker service ls | awk '{print $2}' | grep nextcloud
  changed_when: nextcloud_status.rc == 1
  ignore_errors: true
  failed_when: nextcloud_status.rc == 2
  register: nextcloud_status 

- name: Create nextcloud volume root directory
  hosts: nfs-server[0]
  become: "yes"
  file:
    path: /srv/nfs/nextcloud
    state: directory
    mode: 0777
  any_errors_fatal: true
  when: nextcloud_status.rc == 1
  
- name: Create nextcloud volume data directory
  hosts: nfs-server[0]
  become: "yes"
  file:
    path: /srv/nfs/nextcloud/config
    state: directory
    mode: 0777
  any_errors_fatal: true
  when: nextcloud_status.rc == 1
  
- name: Create nextcloud volume data directory
  hosts: nfs-server[0]
  become: "yes"
  file:
    path: /srv/nfs/nextcloud/data
    state: directory
    mode: 0777
  any_errors_fatal: true
  when: nextcloud_status.rc == 1

- name: Create nextcloud volume data directory
  hosts: nfs-server[0]
  become: "yes"
  file:
    path: /srv/nfs/nextcloud/custom_apps
    state: directory
    mode: 0777
  any_errors_fatal: true
  when: nextcloud_status.rc == 1

- name: Create nextcloud db user
  connection: local
  postgresql_user: 
    login_host: postgres
    login_password: dbadmin
    user: nextcloud
    password: 'str[\"md5\"] + md5[ nextadmin + nextcloud ]'
    encrypted: "yes"
    state: present
  when: nextcloud_status.rc == 1

- name: Setup nextcloud database on db server
  connection: local
  postgresql_db:
    login_host: postgres
    login_password: dbadmin
    name: nextcloud
    owner: nextcloud
    state: present
  when: nextcloud_status.rc == 1

- name: Deploy nextcloud service
  hosts: docker-manager[0]
  command: | 
    docker service create -d --name nextcloud \
    --network mangonet \
    --label treafik.port=80 \
    --mount type=bind,src=/srv/docker-volumes/nextcloud/config,dst=/var/wwww/html/config \
    --mount type=bind,src=/srv/docker-volumes/nextcloud/data,dst=/var/wwww/html/data \
    --mount type=bind,src=/srv/docker-volumes/nextcloud/custom_apps,dst=/var/wwww/html/custom_apps \
    -e POSTGRES_DB=nextcloud \
    -e POSTGRES_USER=nextcloud
    -e POSTGRES_PASSWORD=nextadmin \
    -e POSTGRES_HOST=postgres:5432 \
    -e NEXTCLOUD_ADMIN_USER=sysmango \
    -e NEXTCLOUD_ADMIN_PASSWORD=Atr0c1ty! \
    -e NEXTCLOUD_REDIS_ENABLED=true \
    -e NEXTCLOUD_REDIS_HOST=redis \
    --replicas 1 \
    nextcloud:latest  
  run_once: true
  when: nextcloud_status.rc == 1

#    --publish 8082:80 \

- name: Register nextcloud name with Route53
  connection: local
  route53:
    state: present
    zone: sysmango.net
    record: nextcloud.sysmango.net
    type: A
    value: 192.168.1.143,192.168.1.224,192.168.1.201
    overwrite: "yes"
    wait: "yes"